### ISSUE TITLE
Fix trimming once mpc attempts to echo a non-audio file

### ISSUE THREAD

**Issue by wrjac** [russell190/configfiles#4]
See my latest [commit](https://github.com/russell190/configfiles/commit/ece77d242ec2a3de035cd8cc2143511898f25ab2#diff-8ac33a6537ecfb91b326f32cc9d7a2de) at line [14](https://github.com/russell190/configfiles/commit/ece77d242ec2a3de035cd8cc2143511898f25ab2#diff-8ac33a6537ecfb91b326f32cc9d7a2deL14). Trimming works as it should until my music player daemon reads a file that is not of audio format. Once this occurs, an exception is thrown within the mpc script that throws off the head and tail of my trimming.  This in turn will no longer echo "playing", and instead echoes something unwarranted

**Comment by russell190** [comment]
Should be """fixed""" [hurr](https://github.com/russell190/configfiles/commit/f497bda63fdca8d825248f5350ac34da60d9b939).

**Comment by wrjac** [comment]
Should be """fixed""" [hurr](https://github.com/russell190/configfiles/commit/f497bda63fdca8d825248f5350ac34da60d9b939).
